apiVersion: v1
kind: ServiceAccount
metadata:
  name: quobyte-csi-node-plugin
  namespace: quobyte
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-node
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quobyte-csi-node
subjects:
  - kind: ServiceAccount
    name: quobyte-csi-node-plugin
    namespace: quobyte
roleRef:
  kind: ClusterRole
  name: quobyte-csi-node
  apiGroup: rbac.authorization.k8s.io
